version: '3'

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - app-network

  wordpress:
    depends_on: 
      - mariadb
    build : ./requirements/wordpress/
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
    

  nginx:
    depends_on:
      - wordpress
    build : ./requirements/nginx/
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aali-mou/data/db
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aali-mou/data/wp

networks:
  app-network:
    driver: bridge